### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

spring.datasource:
    url: jdbc:mysql://210.120.247.140:3306/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: coupon
    password: coupon@DBPW
spring.jpa:
    hibernate.ddl-auto: create-drop
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    jpa.show-sql: true
    hibernate.format_sql: TRUE
# spring conf
spring:
    application.name: spring-boot-thymeleaf
    thymeleaf:
        cache: false

# logging conf
logging:
    level:
        org.springframework.web: INFO
        com.example.boot.thymeleaf: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor: TRACE

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-example
  version: 0.1
  description: boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}


